baseURL = "https://opa-test.netlify.app"
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "6"
summaryLength = "10"
theme = "twentytwenty"
title = "Open Post Academics"
[markup.goldmark.renderer]
unsafe = true
[menu]
desktop = []
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "contact"
name = "Join Us"
weight = 4
[[menu.main]]
URL = "sample-page"
name = "Sample Page"
weight = 5
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Open Post Academics"
description = "We are an international, interdisciplinary, collaborative, peer-led community that empowers people with a PhD to bring their knowledge and expertise to the world."
[params.banner]
heading = "Open Post Academics"
image = "/images/bd_flame.jpg"
[params.blog]
heading = "We are an international, interdisciplinary, collaborative, peer-led community that empowers people with a PhD to bring their knowledge and expertise to the world."
[params.call_to_action]
button_label = "Sign Up"
button_url = "https://www.mixily.com/listing/12405727515612781"
content = "We regularly run events for people with a PhD. Join us for our weekly coffee chats or for workshops on the many facets of leaving academia."
enable = true
title = "Upcoming Events"
[params.cookies]
enable = true
expire_days = 2
[params.footer]
address = "123 Main Street <br> New York, NY 10001"
content = "This may be a good place to introduce yourself and your site or include some credits."
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com) ported from [WordPress Twenty Twenty](https://github.com/WordPress/twentytwenty)"
hours = "Monday–Friday: 9:00AM–5:00PM <br> Saturday & Sunday: 11:00AM–3:00PM"
title = "About This Site"
[params.gallery]
enable = false
[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"
[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"
[params.social]
email = "#"
facebook = "#"
instagram = "#"
linkedin = "#"
twitter = "#"
yelp = "#"
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
