baseURL = "https://openpostac.org"
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "6"
summaryLength = "10"
theme = "twentytwenty"
title = "Open Post Academics"
[markup.goldmark.renderer]
unsafe = true
[[menu.desktop]]
URL = "contact"
name = "Join Us"
weight = 2
[[menu.desktop]]
URL = "about"
name = "About"
weight = 1
[[menu.main]]
URL = "contact"
name = "Join Us"
weight = 4
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 5
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Open Post Academics"
description = "Empowering people with a PhD to bring their knowledge and expertise to the world"
[params.banner]
heading = "Open Post Academics"
image = "/images/bd_flame_header.jpg"
[params.blog]
heading = "Empowering people with a PhD to bring their knowledge and expertise to the world"
[params.call_to_action]
button_label = "Sign Up"
button_url = "https://www.mixily.com/listing/12405727515612781"
content = "We regularly run events for people with a PhD. Join us for our weekly coffee chats or for workshops on the many facets of leaving academia."
enable = true
title = "Upcoming Events"
[params.cookies]
enable = false
expire_days = 2
[params.footer]
address = ""
content = ""
copyright = "Open Post Academics (OPA) 2021 CC BY 4.0. Except where otherwise noted, this work is licensed under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/). Built with the [WordPress Twenty Twenty](https://github.com/WordPress/twentytwenty) template, ported to Hugo by [themefisher](https://themefisher.com)."
hours = ""
title = ""
[params.gallery]
enable = false
[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"
[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"
[params.social]
email = ""
facebook = ""
instagram = ""
linkedin = ""
twitter = ""
yelp = ""
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
